/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Cloud Cost Management API
 * API for managing cloud costs, tracking usage, and organizing services into projects.
 * OpenAPI spec version: 1.0.0
 */

export type AwsRDSEngineEnum = typeof AwsRDSEngineEnum[keyof typeof AwsRDSEngineEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AwsRDSEngineEnum = {
  aurora_mysql: 'aurora_mysql',
  aurora_postgresql: 'aurora_postgresql',
  mysql: 'mysql',
  postgresql: 'postgresql',
} as const;
