/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Cloud Cost Management API
 * API for managing cloud costs, tracking usage, and organizing services into projects.
 * OpenAPI spec version: 1.0.0
 */
import type { AwsRDSEngineEnum } from './awsRDSEngineEnum';

export interface AwsRDSEngine {
  engine: AwsRDSEngineEnum;
}
