/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Cloud Cost Management API
 * API for managing cloud costs, tracking usage, and organizing services into projects.
 * OpenAPI spec version: 1.0.0
 */

export type GetAwsEc2Instances200Item = {
  id?: string;
  instancefamily?: string;
  instancetype?: string;
  memory?: number;
  ondemandprice?: number;
  vcpu?: number;
};
