/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Cloud Cost Management API
 * API for managing cloud costs, tracking usage, and organizing services into projects.
 * OpenAPI spec version: 1.0.0
 */

export type GetAwsRdsInstancesInstanceSku200 = {
  clockspeed?: string;
  database_engine?: string;
  dedicated_ebs_throughput?: string;
  id?: string;
  instance_family?: string;
  instance_type?: string;
  memory?: number;
  networkper_formance?: string;
  ondemand_price?: number;
  one_year_reserved_standard_price?: number;
  physical_processor?: string;
  region?: string;
  storage?: string;
  three_year_reserved_standard_price?: number;
  vcpu?: number;
};
