/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Cloud Cost Management API
 * API for managing cloud costs, tracking usage, and organizing services into projects.
 * OpenAPI spec version: 1.0.0
 */

export type GetAwsEc2InstancesInstanceSku200 = {
  clockspeed?: string;
  dedicatedebs_throughput?: string;
  ecu?: number;
  gpu_memory?: number;
  id?: string;
  instance_family?: string;
  instance_type?: string;
  memory?: number;
  networkper_formance?: string;
  ondemand_price?: number;
  one_year_reserved_convertible_price?: number;
  one_year_reserved_standard_price?: number;
  os?: string;
  physical_processor?: string;
  processor_features?: string;
  region?: string;
  storage?: string;
  three_year_reserved_convertible_price?: number;
  three_year_reserved_standard_price?: number;
  vcpu?: number;
};
