/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Cloud Cost Management API
 * API for managing cloud costs, tracking usage, and organizing services into projects.
 * OpenAPI spec version: 1.0.0
 */

export type GetAwsRdsInstances200Item = {
  database_engine?: string;
  id?: string;
  instance_family?: string;
  instance_type?: string;
  memory?: number;
  ondemandprice?: number;
  regioncode?: string;
  vcpu?: number;
};
