/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Cloud Cost Management API
 * API for managing cloud costs, tracking usage, and organizing services into projects.
 * OpenAPI spec version: 1.0.0
 */
import type { AWSRegion } from './aWSRegion';
import type { Os } from './os';

export type GetAwsEc2InstancesParams = {
/**
 * Filter instance by region
 */
region?: AWSRegion;
/**
 * Filter instance by name
 */
os?: Os;
/**
 * Filter instance by type
 */
instancetype?: string;
};
