/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Cloud Cost Management API
 * API for managing cloud costs, tracking usage, and organizing services into projects.
 * OpenAPI spec version: 1.0.0
 */

export type OsEnum = typeof OsEnum[keyof typeof OsEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OsEnum = {
  linux: 'linux',
  windows: 'windows',
} as const;
